apiVersion: batch/v1
kind: Job
metadata:
  name: test-app
spec:
  template:
    spec:
      containers:
      - name: test-app
        image: gcr.io/nhaminh-251901/testapp:0.0.1
        command: ["python", "-u", "test_app.py"]
      restartPolicy: Never
  backoffLimit: 4